import { createFileRoute } from "@tanstack/react-router";
import { InfoPage, meta } from "@/components/intervue-you/info-page";

export const Route = createFileRoute("/terms")({
  head: () => meta("Terms of Service", "The terms that apply when you use  Intervue You for interview practice."),
  component: () => (
    <InfoPage
      eyebrow="Legal"
      title="Terms of Service"
      intro="These terms explain how you may use  Intervue You. By creating an account you agree to them."
      sections={[
        { h: "Using  Intervue You", p: " Intervue You is a practice tool. You agree not to use it to receive hidden assistance during real interviews or assessments." },
        { h: "Your account", p: "Keep your login details safe. You're responsible for activity on your account." },
        { h: "Subscriptions", p: "Paid plans renew automatically until cancelled. You can cancel anytime in Settings and keep access until the end of the billing period." },
        { h: "AI feedback", p: "Scores and feedback are generated by AI and are guidance, not a guarantee of any hiring outcome." },
      ]}
    />
  ),
});
